import { ReactNode } from "react";

//interface for results from spotify api
export interface Results {
  artists: any;
  name: ReactNode;
  album: any;
  tracks: {
    items: any[];
  };
}

duplicateSongs = [
  {
    added_at: "2022-08-01T09:58:39Z",
    added_by: {
      external_urls: {
        spotify: "https://open.spotify.com/user/113647088",
      },
      href: "https://api.spotify.com/v1/users/113647088",
      id: "113647088",
      type: "user",
      uri: "spotify:user:113647088",
    },
    is_local: false,
    primary_color: null,
    track: {
      album: {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/19SmlbABtI4bXz864MLqOS",
            },
            href: "https://api.spotify.com/v1/artists/19SmlbABtI4bXz864MLqOS",
            id: "19SmlbABtI4bXz864MLqOS",
            name: "Carl Cox",
            type: "artist",
            uri: "spotify:artist:19SmlbABtI4bXz864MLqOS",
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0EAlTKO2HfATH766bVH1rX",
            },
            href: "https://api.spotify.com/v1/artists/0EAlTKO2HfATH766bVH1rX",
            id: "0EAlTKO2HfATH766bVH1rX",
            name: "Josh Butler",
            type: "artist",
            uri: "spotify:artist:0EAlTKO2HfATH766bVH1rX",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/5UaviWt00UWkUA4xkWsCes",
        },
        href: "https://api.spotify.com/v1/albums/5UaviWt00UWkUA4xkWsCes",
        id: "5UaviWt00UWkUA4xkWsCes",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b2739b3a2a4af5953df71fbb7506",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e029b3a2a4af5953df71fbb7506",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d000048519b3a2a4af5953df71fbb7506",
            width: 64,
          },
        ],
        name: "I Want You (Forever) [Josh Butler Remix]",
        release_date: "2017-09-01",
        release_date_precision: "day",
        total_tracks: 2,
        type: "album",
        uri: "spotify:album:5UaviWt00UWkUA4xkWsCes",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/19SmlbABtI4bXz864MLqOS",
          },
          href: "https://api.spotify.com/v1/artists/19SmlbABtI4bXz864MLqOS",
          id: "19SmlbABtI4bXz864MLqOS",
          name: "Carl Cox",
          type: "artist",
          uri: "spotify:artist:19SmlbABtI4bXz864MLqOS",
        },
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/0EAlTKO2HfATH766bVH1rX",
          },
          href: "https://api.spotify.com/v1/artists/0EAlTKO2HfATH766bVH1rX",
          id: "0EAlTKO2HfATH766bVH1rX",
          name: "Josh Butler",
          type: "artist",
          uri: "spotify:artist:0EAlTKO2HfATH766bVH1rX",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AO",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CD",
        "CG",
        "CH",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IQ",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MG",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TJ",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VE",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZM",
        "ZW",
      ],
      disc_number: 1,
      duration_ms: 245714,
      episode: false,
      explicit: false,
      external_ids: {
        isrc: "GBHAD1700209",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/6A2fGSY2uZcidWpNosshqc",
      },
      href: "https://api.spotify.com/v1/tracks/6A2fGSY2uZcidWpNosshqc",
      id: "6A2fGSY2uZcidWpNosshqc",
      is_local: false,
      name: "I Want You (Forever) - Josh Butler Remix - Radio Edit",
      popularity: 62,
      preview_url:
        "https://p.scdn.co/mp3-preview/f82f243fe1f8924d48a5cf5c8e0a1cddecd6ab3c?cid=54dece4e1c44405d8832f941bacc28a0",
      track: true,
      track_number: 2,
      type: "track",
      uri: "spotify:track:6A2fGSY2uZcidWpNosshqc",
    },
    video_thumbnail: {
      url: null,
    },
  },
];
